// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package manyminds.datamodel;

public final class DataServerDispatch_Stub
    extends java.rmi.server.RemoteStub
    implements manyminds.datamodel.RemoteDataServerDispatch, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_autosaveData_0;
    private static java.lang.reflect.Method $method_getAllDataNames_1;
    private static java.lang.reflect.Method $method_getAllLogfileNames_2;
    private static java.lang.reflect.Method $method_getDataNames_3;
    private static java.lang.reflect.Method $method_getDataServer_4;
    private static java.lang.reflect.Method $method_getFile_5;
    private static java.lang.reflect.Method $method_newDataServer_6;
    private static java.lang.reflect.Method $method_saveAllData_7;
    
    static {
	try {
	    $method_autosaveData_0 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("autosaveData", new java.lang.Class[] {});
	    $method_getAllDataNames_1 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("getAllDataNames", new java.lang.Class[] {});
	    $method_getAllLogfileNames_2 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("getAllLogfileNames", new java.lang.Class[] {});
	    $method_getDataNames_3 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("getDataNames", new java.lang.Class[] {});
	    $method_getDataServer_4 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("getDataServer", new java.lang.Class[] {java.lang.String.class});
	    $method_getFile_5 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("getFile", new java.lang.Class[] {java.lang.String.class});
	    $method_newDataServer_6 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("newDataServer", new java.lang.Class[] {java.lang.String.class});
	    $method_saveAllData_7 = manyminds.datamodel.RemoteDataServerDispatch.class.getMethod("saveAllData", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public DataServerDispatch_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of autosaveData()
    public void autosaveData()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_autosaveData_0, null, 5595199379591521155L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllDataNames()
    public java.lang.String[] getAllDataNames()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllDataNames_1, null, 6598318259638380687L);
	    return ((java.lang.String[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllLogfileNames()
    public java.lang.String[] getAllLogfileNames()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllLogfileNames_2, null, -5314032752321383680L);
	    return ((java.lang.String[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDataNames()
    public java.lang.String[] getDataNames()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDataNames_3, null, 702751068843793974L);
	    return ((java.lang.String[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDataServer(String)
    public manyminds.datamodel.RemoteDataServer getDataServer(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDataServer_4, new java.lang.Object[] {$param_String_1}, 7355159001296579471L);
	    return ((manyminds.datamodel.RemoteDataServer) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFile(String)
    public byte[] getFile(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFile_5, new java.lang.Object[] {$param_String_1}, -3821082806462039528L);
	    return ((byte[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of newDataServer(String)
    public manyminds.datamodel.RemoteDataServer newDataServer(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_newDataServer_6, new java.lang.Object[] {$param_String_1}, 6507143971139583846L);
	    return ((manyminds.datamodel.RemoteDataServer) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveAllData()
    public void saveAllData()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_saveAllData_7, null, -5973558203060961625L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
