// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package manyminds.datamodel;

public final class ManyMindsDocument_Stub
    extends java.rmi.server.RemoteStub
    implements manyminds.datamodel.RemoteData, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_forgetDownstreamPeers_0;
    private static java.lang.reflect.Method $method_forgetUpstreamPeers_1;
    private static java.lang.reflect.Method $method_peerConnectDownstream_2;
    private static java.lang.reflect.Method $method_peerConnectUpstream_3;
    private static java.lang.reflect.Method $method_peerDisconnectDownstream_4;
    private static java.lang.reflect.Method $method_peerDisconnectUpstream_5;
    private static java.lang.reflect.Method $method_peerGetType_6;
    private static java.lang.reflect.Method $method_peerGetTypeString_7;
    private static java.lang.reflect.Method $method_peerGetValue_8;
    private static java.lang.reflect.Method $method_peerSetTypeString_9;
    private static java.lang.reflect.Method $method_peerValueChanged_10;
    
    static {
	try {
	    $method_forgetDownstreamPeers_0 = manyminds.datamodel.RemoteData.class.getMethod("forgetDownstreamPeers", new java.lang.Class[] {});
	    $method_forgetUpstreamPeers_1 = manyminds.datamodel.RemoteData.class.getMethod("forgetUpstreamPeers", new java.lang.Class[] {});
	    $method_peerConnectDownstream_2 = manyminds.datamodel.RemoteData.class.getMethod("peerConnectDownstream", new java.lang.Class[] {manyminds.datamodel.RemoteData.class});
	    $method_peerConnectUpstream_3 = manyminds.datamodel.RemoteData.class.getMethod("peerConnectUpstream", new java.lang.Class[] {manyminds.datamodel.RemoteData.class});
	    $method_peerDisconnectDownstream_4 = manyminds.datamodel.RemoteData.class.getMethod("peerDisconnectDownstream", new java.lang.Class[] {manyminds.datamodel.RemoteData.class});
	    $method_peerDisconnectUpstream_5 = manyminds.datamodel.RemoteData.class.getMethod("peerDisconnectUpstream", new java.lang.Class[] {manyminds.datamodel.RemoteData.class});
	    $method_peerGetType_6 = manyminds.datamodel.RemoteData.class.getMethod("peerGetType", new java.lang.Class[] {});
	    $method_peerGetTypeString_7 = manyminds.datamodel.RemoteData.class.getMethod("peerGetTypeString", new java.lang.Class[] {});
	    $method_peerGetValue_8 = manyminds.datamodel.RemoteData.class.getMethod("peerGetValue", new java.lang.Class[] {});
	    $method_peerSetTypeString_9 = manyminds.datamodel.RemoteData.class.getMethod("peerSetTypeString", new java.lang.Class[] {java.lang.String.class});
	    $method_peerValueChanged_10 = manyminds.datamodel.RemoteData.class.getMethod("peerValueChanged", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ManyMindsDocument_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of forgetDownstreamPeers()
    public void forgetDownstreamPeers()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_forgetDownstreamPeers_0, null, 6462166020636468669L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of forgetUpstreamPeers()
    public void forgetUpstreamPeers()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_forgetUpstreamPeers_1, null, 1642855818340601754L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerConnectDownstream(RemoteData)
    public void peerConnectDownstream(manyminds.datamodel.RemoteData $param_RemoteData_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_peerConnectDownstream_2, new java.lang.Object[] {$param_RemoteData_1}, -5333112543377358082L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerConnectUpstream(RemoteData)
    public void peerConnectUpstream(manyminds.datamodel.RemoteData $param_RemoteData_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_peerConnectUpstream_3, new java.lang.Object[] {$param_RemoteData_1}, 6015931364369339148L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerDisconnectDownstream(RemoteData)
    public void peerDisconnectDownstream(manyminds.datamodel.RemoteData $param_RemoteData_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_peerDisconnectDownstream_4, new java.lang.Object[] {$param_RemoteData_1}, -8453393186966728387L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerDisconnectUpstream(RemoteData)
    public void peerDisconnectUpstream(manyminds.datamodel.RemoteData $param_RemoteData_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_peerDisconnectUpstream_5, new java.lang.Object[] {$param_RemoteData_1}, 8933203733362543108L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerGetType()
    public int peerGetType()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_peerGetType_6, null, -621709264303832041L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerGetTypeString()
    public java.lang.String peerGetTypeString()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_peerGetTypeString_7, null, 6296751151505941248L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerGetValue()
    public java.lang.String peerGetValue()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_peerGetValue_8, null, -5306632451454523486L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerSetTypeString(String)
    public void peerSetTypeString(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_peerSetTypeString_9, new java.lang.Object[] {$param_String_1}, 2215668457058040363L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of peerValueChanged(String, String)
    public void peerValueChanged(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_peerValueChanged_10, new java.lang.Object[] {$param_String_1, $param_String_2}, -1391522240517096277L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
