/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class manyminds_util_browser_WebKitComponent */

#ifndef _Included_manyminds_util_browser_WebKitComponent
#define _Included_manyminds_util_browser_WebKitComponent
#ifdef __cplusplus
extern "C" {
#endif
#undef manyminds_util_browser_WebKitComponent_FOCUS_TRAVERSABLE_UNKNOWN
#define manyminds_util_browser_WebKitComponent_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef manyminds_util_browser_WebKitComponent_FOCUS_TRAVERSABLE_DEFAULT
#define manyminds_util_browser_WebKitComponent_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef manyminds_util_browser_WebKitComponent_FOCUS_TRAVERSABLE_SET
#define manyminds_util_browser_WebKitComponent_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef manyminds_util_browser_WebKitComponent_TOP_ALIGNMENT
#define manyminds_util_browser_WebKitComponent_TOP_ALIGNMENT 0.0f
#undef manyminds_util_browser_WebKitComponent_CENTER_ALIGNMENT
#define manyminds_util_browser_WebKitComponent_CENTER_ALIGNMENT 0.5f
#undef manyminds_util_browser_WebKitComponent_BOTTOM_ALIGNMENT
#define manyminds_util_browser_WebKitComponent_BOTTOM_ALIGNMENT 1.0f
#undef manyminds_util_browser_WebKitComponent_LEFT_ALIGNMENT
#define manyminds_util_browser_WebKitComponent_LEFT_ALIGNMENT 0.0f
#undef manyminds_util_browser_WebKitComponent_RIGHT_ALIGNMENT
#define manyminds_util_browser_WebKitComponent_RIGHT_ALIGNMENT 1.0f
#undef manyminds_util_browser_WebKitComponent_serialVersionUID
#define manyminds_util_browser_WebKitComponent_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: nameCounter */
#undef manyminds_util_browser_WebKitComponent_serialVersionUID
#define manyminds_util_browser_WebKitComponent_serialVersionUID -2284879212465893870LL
#undef manyminds_util_browser_WebKitComponent_storeJavaObject
#define manyminds_util_browser_WebKitComponent_storeJavaObject 1L
#undef manyminds_util_browser_WebKitComponent_loadURL
#define manyminds_util_browser_WebKitComponent_loadURL 2L
#undef manyminds_util_browser_WebKitComponent_goBack
#define manyminds_util_browser_WebKitComponent_goBack 3L
#undef manyminds_util_browser_WebKitComponent_goForward
#define manyminds_util_browser_WebKitComponent_goForward 4L
#undef manyminds_util_browser_WebKitComponent_reloadPage
#define manyminds_util_browser_WebKitComponent_reloadPage 5L
/*
 * Class:     manyminds_util_browser_WebKitComponent
 * Method:    createNSView
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_manyminds_util_browser_WebKitComponent_createNSView
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
