// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package manyminds.communication;

public final class Mailbox_Stub
    extends java.rmi.server.RemoteStub
    implements manyminds.communication.RemoteMailbox, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_deliver_0;
    
    static {
	try {
	    $method_deliver_0 = manyminds.communication.RemoteMailbox.class.getMethod("deliver", new java.lang.Class[] {manyminds.communication.Message.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Mailbox_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of deliver(Message)
    public void deliver(manyminds.communication.Message $param_Message_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deliver_0, new java.lang.Object[] {$param_Message_1}, 1995329984622321356L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
