// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package manyminds.communication;

public final class PostOffice_Stub
    extends java.rmi.server.RemoteStub
    implements manyminds.communication.RemotePostOffice, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_register_0;
    private static java.lang.reflect.Method $method_send_1;
    private static java.lang.reflect.Method $method_unregister_2;
    
    static {
	try {
	    $method_register_0 = manyminds.communication.RemotePostOffice.class.getMethod("register", new java.lang.Class[] {manyminds.communication.RemoteMailbox.class, java.lang.String.class});
	    $method_send_1 = manyminds.communication.RemotePostOffice.class.getMethod("send", new java.lang.Class[] {manyminds.communication.Message.class});
	    $method_unregister_2 = manyminds.communication.RemotePostOffice.class.getMethod("unregister", new java.lang.Class[] {manyminds.communication.RemoteMailbox.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PostOffice_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of register(RemoteMailbox, String)
    public void register(manyminds.communication.RemoteMailbox $param_RemoteMailbox_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_register_0, new java.lang.Object[] {$param_RemoteMailbox_1, $param_String_2}, -3903377227780628058L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of send(Message)
    public boolean send(manyminds.communication.Message $param_Message_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_send_1, new java.lang.Object[] {$param_Message_1}, -2627570871880050044L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of unregister(RemoteMailbox)
    public void unregister(manyminds.communication.RemoteMailbox $param_RemoteMailbox_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_unregister_2, new java.lang.Object[] {$param_RemoteMailbox_1}, -440713937631246326L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
